version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Expose backend port
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mysql@123
      - DB_NAME=employee_management
    depends_on:
      - mysql
    volumes:
      - ./backend:/app  # Mount backend code inside the container for live reload

  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Expose frontend port for development mode
    volumes:
      - ./frontend:/app  # Mount frontend code inside the container for live reload
    environment:
      - CHOKIDAR_USEPOLLING=true  # Fix for file watching issues in Docker
    command: ["npm", "run", "dev"]  # Run the frontend in development mode

  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"  # Expose MySQL port
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: employee_management
    volumes:
      - db_data:/var/lib/mysql  # Persist database data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql  # Initialize the database with a script

volumes:
  db_data:  # Volume to persist MySQL data
